package strategy;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.draw.LineSeparator;

import java.io.FileOutputStream;
import java.io.File;

/**
 * Strategy Pattern — ITextRenderingStrategy
 *
 * Real PDF generation using the iText 5 library.
 * Produces an actual .pdf file with title, metadata, and content paragraphs.
 *
 * This is the ONLY class that changed to go from simulated to real PDF output.
 * The Factory, Template, and Decorator did not change at all —
 * which is exactly what the Strategy pattern guarantees.
 */
public class ITextRenderingStrategy implements RenderingStrategy {

    private static final String EXPORTS_DIR = "exports";

    @Override
    public String render(String documentContent) {
        System.out.println("[Template]   Step 2: Rendering content (iText engine)... OK");

        new File(EXPORTS_DIR).mkdirs();
        String pdfPath = EXPORTS_DIR + File.separator + "Q3_Financial_Report.pdf";

        try {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream(pdfPath));
            document.open();

            // Title
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);
            Paragraph title = new Paragraph("Document Export System", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Subtitle
            Font subFont = new Font(Font.FontFamily.HELVETICA, 13, Font.ITALIC, BaseColor.DARK_GRAY);
            Paragraph sub = new Paragraph("Generated by ITextRenderingStrategy", subFont);
            sub.setAlignment(Element.ALIGN_CENTER);
            sub.setSpacingAfter(30);
            document.add(sub);

            // Divider line
            LineSeparator line = new LineSeparator();
            document.add(new Chunk(line));
            document.add(Chunk.NEWLINE);

            // Content section
            Font sectionFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            document.add(new Paragraph("Export Content", sectionFont));
            document.add(Chunk.NEWLINE);

            Font bodyFont = new Font(Font.FontFamily.HELVETICA, 11);
            document.add(new Paragraph(documentContent, bodyFont));
            document.add(Chunk.NEWLINE);

            // Pattern info section
            document.add(new Paragraph("Design Pattern Details", sectionFont));
            document.add(Chunk.NEWLINE);

            String[][] rows = {
                {"Pattern",   "Class",                     "Role"},
                {"Factory",   "ExporterFactory",           "Created this PdfExporter"},
                {"Template",  "AbstractExporter",          "Ran the 4-step pipeline"},
                {"Strategy",  "ITextRenderingStrategy",    "Rendered this PDF (you are here)"},
                {"Decorator", "Compress + Encrypt + Mark", "Applied post-processing"}
            };

            PdfPTable table = new PdfPTable(3);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10);

            for (int r = 0; r < rows.length; r++) {
                for (String cell : rows[r]) {
                    PdfPCell c = new PdfPCell(new Phrase(cell,
                            r == 0 ? sectionFont : bodyFont));
                    c.setPadding(6);
                    if (r == 0) c.setBackgroundColor(new BaseColor(220, 230, 255));
                    table.addCell(c);
                }
            }
            document.add(table);

            document.close();
            System.out.println("[Template]   Step 2: Real PDF created --> " + pdfPath);

} catch (Exception e) {
    System.out.println("[PDF ERROR] " + e.getClass().getName() + ": " + e.getMessage());
    for (StackTraceElement s : e.getStackTrace()) {
        System.out.println("  at " + s);
    }
}

        return "PDF content: " + documentContent;
    }

    @Override
    public double getSizeMb() { return 2.4; }

    @Override
    public String getEngineName() { return "ITextRenderingStrategy"; }
}
